### PR TITLE
[#6566] Fix JSON statistics

### LINKED ISSUE #6566: [ERROR] statistics#index (NoMethodError) undefined method `each' for nil:NilClass
```
A NoMethodError occurred in statistics#index:

  undefined method `each' for nil:NilClass
  app/models/statistics.rb:112:in `user_json_for_api'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/statistics.json
  * HTTP Method: GET
  * Parameters : {"controller"=>"statistics", "action"=>"index", "format"=>"json"}
  * Timestamp  : 2021-10-11 11:58:58 +0100
  * Process: 10205

-------------------------------
Backtrace:
-------------------------------

  app/models/statistics.rb:112:in `user_json_for_api'
  app/controllers/statistics_controller.rb:21:in `block (2 levels) in index'
  app/controllers/statistics_controller.rb:16:in `index'
  app/controllers/application_controller.rb:111:in `record_memory'
  lib/deeply_nested_params.rb:15:in `call'
  lib/strip_empty_sessions.rb:14:in `call'

```

### PR DESCRIPTION
**Pull request by gbp**
## Relevant issue(s)

Fixes #6566

## What does this do?

Fix JSON statistics

## Why was this needed?

Broken since #6523 where a instance variable was renamed in the HTML
response but not the JSON response. Also added spec to check the format
of the JSON response.

### CODE REVIEW

**Review by garethrees — APPROVED** [review]
Haven't run but looks sensible 👍
