### ISSUE TITLE
[ERROR] admin_user#banned (NoMethodError) "undefined method `order'

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#4804]
```
A NoMethodError occurred in admin_user#banned:

undefined method `order' for #<AdminUserController:0x00007fb89c33f340>
app/controllers/admin_user_controller.rb:88:in `banned'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/admin/users/banned
* HTTP Method: GET
* Parameters : {"controller"=>"admin_user", "action"=>"banned"}
* Timestamp : 2018-08-13 18:53:19 +0100

-------------------------------
Backtrace:
-------------------------------

app/controllers/admin_user_controller.rb:88:in `banned'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

Missing method chaining `.` introduced in https://github.com/mysociety/alaveteli/commit/d2f1d9763931c00ba08f9c585c07221e3e9ec52e.
