### ISSUE TITLE
[ERROR] ActionView::Template::Error occurred in request#show "undefined method `to_key' for nil:NilClass"

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#7358]
```
-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/foi_request_for_bailiffs_and_cou_6
  * HTTP Method: GET
  * Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"foi_request_for_bailiffs_and_cou_6"}


-------------------------------
Backtrace:
-------------------------------

  app/helpers/link_to_helper.rb:320:in `dom_id'
  app/views/request/_attachments.html.erb:39
  app/views/request/_incoming_correspondence.html.erb:26
  app/views/request/events/_response.html.erb:1
  app/views/request/_correspondence.html.erb:5
  lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:47
  lib/themes/whatdotheyknow-theme/lib/views/request/show.html.erb:45
  app/controllers/request_controller.rb:100:in `block (3 levels) in show'
  app/controllers/request_controller.rb:99:in `block in show'
  lib/alaveteli_localization.rb:46:in `with_locale'
  app/controllers/request_controller.rb:50:in `show'
  app/controllers/application_controller.rb:111:in `record_memory'
  lib/deeply_nested_params.rb:15:in `call'
  lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
Bug introduced in https://github.com/mysociety/alaveteli/commit/9eb2ee5079

Some multipart emails don't contain plain text part and `IncomingMessage#get_main_body_text_part` is `nil`.
